project:
  type: website
  output-dir: docs
  
website:
  title: "MIRBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jo-cho/mir_kr
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

