project:
  type: website
  output-dir: docs
  
website:
  title: "조조의 음악정보검색 입문"
  site-url: https://jo-cho.github.io/MIRBlog/
  description: "음악정보검색 공부 블로그"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jo-cho/
format:
  html:
    theme: flatly
    css: styles.css
    fontsize: 1.0em

editor: visual

